# Generated by Django 6.0.5 on 2026-05-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.CharField(choices=[('aline', 'Fisioterapia - Aline'), ('gustavo', 'Funcional - Gustavo')], default='aline', max_length=20),
            preserve_default=False,
        ),
    ]
