# Generated by Django 6.0.5 on 2026-05-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('avaliacao', 'Avaliação'), ('atendimento', 'Atendimento')], default='avaliacao', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.CharField(choices=[('aline', 'Fisioterapia - Aline'), ('gustavo', 'Gustavo')], max_length=20),
        ),
    ]
